Add the kasten-pres-ync job

diff --git a/base/kasten-pre-sync-job.yaml b/base/kasten-pre-sync-job.yaml
--- a/base/kasten-pre-sync-job.yaml
+++ b/base/kasten-pre-sync-job.yaml
@@ -23,7 +23,7 @@ spec:
           - |
             # create a bcakup action on the project 
             backup_name="mysqlapp-backup-$(date| tr ' ' '-'|tr ':' '-'|tr '[:upper:]' '[:lower:]')"
-            cat <<EOF | oc create -f -
+            cat <<EOF | kubectl create -f -
             apiVersion: actions.kio.kasten.io/v1alpha1
             kind: BackupAction
             metadata:  
@@ -35,6 +35,29 @@ spec:
                 name: $NAMESPACE
                 namespace: $NAMESPACE
             EOF
+            
+            # Wait until the backucp action is complete 
+            count=15
+            delay=3
+            total_time=$((count*delay))
+            while true 
+            do
+              state=$(kubectl get backupaction -n $NAMESPACE $backup_name -o jsonpath='{.status.state}')
+              if [ "$state" =  "Complete" ]
+              then 
+                echo "backup action $backup_name is Complete"                
+                break
+              else 
+                echo "backup action $backup_name is ${state}"
+                count=$((count-1))
+                sleep $delay
+              fi
+              if [ $count = 0 ] 
+              then 
+                echo "fail to get backup action $backup_name Complete after ${total_time} seconds"
+                exit 1 
+              fi
+            done 
           env:          
           - name: NAMESPACE
             valueFrom:
